adapt job for compose also

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,9 +9,9 @@ services:
   - docker
 
 stages:
-  - name: 6.2.N_values.yaml
-  - name: 6.1.N_values.yaml
-  - name: 6.0.N_values.yaml
+  - name: 6.2.N
+  - name: 6.1.N
+  - name: 6.0.N
 
 import:
   - source: Alfresco/alfresco-process-tools:.travis.helm.yml@master
@@ -77,11 +77,12 @@ _helm_deploy: &helm_deploy
     export release_name_ingress=ing-${TRAVIS_BUILD_NUMBER}
     export release_name_acs=acs-${TRAVIS_BUILD_NUMBER}
     export values_file=helm/alfresco-content-services/values.yaml
-    if [[ ${TRAVIS_JOB_NAME} != "Deploy Latest Chart and Run Postman Checks" ]]; then
-      values_file="helm/alfresco-content-services/${TRAVIS_JOB_NAME}"
+    if [[ ${TRAVIS_BUILD_STAGE_NAME} != "Deploy Latest Chart and Run Postman Checks" ]]; then
+      values_file="helm/alfresco-content-services/${TRAVIS_BUILD_STAGE_NAME}_values.yaml"
     fi
     deploy=false
-    if [[ "${GIT_DIFF}" == *helm/alfresco-content-services/${TRAVIS_JOB_NAME}* ]] || [[ "${GIT_DIFF}" == *helm/alfresco-content-services* ]] && [[ "${GIT_DIFF}" != *helm/alfresco-content-services/*_values.yaml ]] 
+    helm/alfresco-content-services/6.1.N_values.yaml
+    if [[ "${GIT_DIFF}" == *helm/alfresco-content-services/${TRAVIS_BUILD_STAGE_NAME}_values.yaml* ]] || [[ "${GIT_DIFF}" == *helm/alfresco-content-services/templates* ]] || [[ "${GIT_DIFF}" == *helm/alfresco-content-services/charts* ]] || [[ "${GIT_DIFF}" == *helm/alfresco-content-services/requirements* ]]
     then
       deploy=true
     fi
@@ -258,6 +259,86 @@ _helm_deploy: &helm_deploy
     # run checks after pod deletion
     docker run -a STDOUT --volume $PWD/test/postman/helm:/etc/newman --network host postman/newman_alpine33:3.9.2 run "acs-validate-volume-collection.json" --global-var "protocol=https" --global-var "url=$namespace.dev.alfresco.me"
     fi
+_docker_deploy: &docker_deploy
+  script: |
+    values_file="docker-compose/docker-compose.yml"
+    deploy=false
+    if [[ ${TRAVIS_BUILD_STAGE_NAME} != "Deploy Docker Compose and Run Postman Checks" ]]; then
+      values_file="docker-compose/${TRAVIS_BUILD_STAGE_NAME}-docker-compose.yml"
+    fi
+    if [[ "${GIT_DIFF}" == *$values_file* ]]
+    then
+      deploy=true
+    fi
+    if $deploy; then
+    cd docker-compose
+    docker info
+    docker-compose --version
+    docker-compose config
+    echo "Starting Alfresco in Docker container"
+    docker-compose ps
+    docker-compose pull
+    export COMPOSE_HTTP_TIMEOUT=120
+    docker-compose up -d
+    # docker-compose up
+    WAIT_INTERVAL=1
+    COUNTER=0
+    TIMEOUT=300
+    t0=`date +%s`
+    echo "Waiting for alfresco to start"
+    response=$(curl --write-out %{http_code} --output /dev/null --silent http://localhost:8080/alfresco/)
+    until [[ "200" -eq "$response" ]] || [[ "$COUNTER" -eq "$TIMEOUT" ]]; do
+      printf '.'
+      sleep $WAIT_INTERVAL
+      COUNTER=$((COUNTER + WAIT_INTERVAL))
+      response=$(curl --write-out %{http_code} --output /dev/null --silent http://localhost:8080/alfresco/)
+    done
+    if (("$COUNTER" < "$TIMEOUT")) ; then
+      t1=`date +%s`
+      delta=$(((t1 - t0)/60))
+      echo "Alfresco Started in $delta minutes"
+    else
+      echo "Waited $COUNTER seconds"
+      echo "Alfresco could not start in time."
+      echo "The last response code from /alfresco/ was $response"
+      exit 1
+    fi
+    COUNTER=0
+    echo "Waiting for share to start"
+    response=$(curl --write-out %{http_code} --output /dev/null --silent http://localhost:8080/share/page)
+    until [[ "200" -eq "$response" ]] || [[ "$COUNTER" -eq "$TIMEOUT" ]]; do
+      printf '.'
+      sleep $WAIT_INTERVAL
+      COUNTER=$((COUNTER + WAIT_INTERVAL))
+      response=$(curl --write-out %{http_code} --output /dev/null --silent http://localhost:8080/share/page)
+    done
+    if (("$COUNTER" < "$TIMEOUT")) ; then
+      t1=`date +%s`
+      delta=$(((t1 - t0)/60))
+      echo "Share Started in $delta minutes"
+    else
+      echo "Waited $COUNTER seconds"
+      echo "Share could not start in time."
+      echo "The last response code from /share/ was $response"
+      exit 1
+    fi
+    COUNTER=0
+    TIMEOUT=20
+    echo "Waiting more time for SOLR"
+    response=$(curl --write-out %{http_code} --user admin:admin --output /dev/null --silent http://localhost:8080/alfresco/s/api/solrstats)
+    until [[ "200" -eq "$response" ]] || [[ "$COUNTER" -eq "$TIMEOUT" ]]; do
+      printf '.'
+      sleep $WAIT_INTERVAL
+      COUNTER=$((COUNTER + WAIT_INTERVAL))
+      response=$(curl --write-out %{http_code} --user admin:admin --output /dev/null --silent http://localhost:8080/alfresco/s/api/solrstats)
+    done
+    cd ../test/postman/docker-compose
+    docker run -a STDOUT --volume $PWD:/etc/newman --network host postman/newman_alpine33:3.9.2 run "acs-test-docker-compose-collection.json" --insecure --global-var "protocol=http" --global-var "url=localhost:8080"
+    fi
+  after_success: |
+    echo "nothing to cleanup"
+  after_failure: |
+    docker-compose logs --no-color
 
 jobs:
   include:
@@ -268,92 +349,28 @@ jobs:
         helm lint helm/alfresco-content-services/charts/alfresco-search
         helm lint helm/alfresco-content-services/charts/alfresco-sync-service
         helm lint helm/alfresco-content-services/charts/alfresco-search/charts/alfresco-insight-zeppelin
+
     - name: Deploy Docker Compose and Run Postman Checks
       stage: test
-      script: |
-        deploy=false
-        if [[ "${GIT_DIFF}" == *docker-compose/* ]]
-        then
-          deploy=true
-        fi
-        if $deploy; then
-        cd docker-compose
-        docker info
-        docker-compose --version
-        docker-compose config
-        echo "Starting Alfresco in Docker container"
-        docker-compose ps
-        docker-compose pull
-        export COMPOSE_HTTP_TIMEOUT=120
-        docker-compose up -d
-        # docker-compose up
-        WAIT_INTERVAL=1
-        COUNTER=0
-        TIMEOUT=300
-        t0=`date +%s`
-        echo "Waiting for alfresco to start"
-        response=$(curl --write-out %{http_code} --output /dev/null --silent http://localhost:8080/alfresco/)
-        until [[ "200" -eq "$response" ]] || [[ "$COUNTER" -eq "$TIMEOUT" ]]; do
-          printf '.'
-          sleep $WAIT_INTERVAL
-          COUNTER=$((COUNTER + WAIT_INTERVAL))
-          response=$(curl --write-out %{http_code} --output /dev/null --silent http://localhost:8080/alfresco/)
-        done
-        if (("$COUNTER" < "$TIMEOUT")) ; then
-          t1=`date +%s`
-          delta=$(((t1 - t0)/60))
-          echo "Alfresco Started in $delta minutes"
-        else
-          echo "Waited $COUNTER seconds"
-          echo "Alfresco could not start in time."
-          echo "The last response code from /alfresco/ was $response"
-          exit 1
-        fi
-        COUNTER=0
-        echo "Waiting for share to start"
-        response=$(curl --write-out %{http_code} --output /dev/null --silent http://localhost:8080/share/page)
-        until [[ "200" -eq "$response" ]] || [[ "$COUNTER" -eq "$TIMEOUT" ]]; do
-          printf '.'
-          sleep $WAIT_INTERVAL
-          COUNTER=$((COUNTER + WAIT_INTERVAL))
-          response=$(curl --write-out %{http_code} --output /dev/null --silent http://localhost:8080/share/page)
-        done
-        if (("$COUNTER" < "$TIMEOUT")) ; then
-          t1=`date +%s`
-          delta=$(((t1 - t0)/60))
-          echo "Share Started in $delta minutes"
-        else
-          echo "Waited $COUNTER seconds"
-          echo "Share could not start in time."
-          echo "The last response code from /share/ was $response"
-          exit 1
-        fi
-        COUNTER=0
-        TIMEOUT=20
-        echo "Waiting more time for SOLR"
-        response=$(curl --write-out %{http_code} --user admin:admin --output /dev/null --silent http://localhost:8080/alfresco/s/api/solrstats)
-        until [[ "200" -eq "$response" ]] || [[ "$COUNTER" -eq "$TIMEOUT" ]]; do
-          printf '.'
-          sleep $WAIT_INTERVAL
-          COUNTER=$((COUNTER + WAIT_INTERVAL))
-          response=$(curl --write-out %{http_code} --user admin:admin --output /dev/null --silent http://localhost:8080/alfresco/s/api/solrstats)
-        done
-        cd ../test/postman/docker-compose
-        docker run -a STDOUT --volume $PWD:/etc/newman --network host postman/newman_alpine33:3.9.2 run "acs-test-docker-compose-collection.json" --insecure --global-var "protocol=http" --global-var "url=localhost:8080"
-        fi
-      after_success: |
-        echo "nothing to cleanup"
-      after_failure: |
-        docker-compose logs --no-color
+      <<: *docker_deploy
     - name: Deploy Latest Chart and Run Postman Checks
       stage: test
       <<: *helm_deploy
-    - stage: 6.2.N_values.yaml
-      name: 6.2.N_values.yaml
+
+    - stage: 6.2.N
+      name: 6.2.N-helm
       <<: *helm_deploy
-    - stage: 6.1.N_values.yaml
-      name: 6.1.N_values.yaml
+    - name: 6.2.N-compose
+      <<: *docker_deploy
+
+    - stage: 6.1.N
+      name: 6.1.N-helm
       <<: *helm_deploy
-    - stage: 6.0.N_values.yaml
-      name: 6.0.N_values.yaml
+    - name: 6.1.N-compose
+      <<: *docker_deploy
+
+    - stage: 6.0.N
+      name: 6.0.N-helm
       <<: *helm_deploy
+    - name: 6.0.N-compose
+      <<: *docker_deploy
