Check test results as we go

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -244,30 +244,35 @@ _helm_deploy: &helm_deploy
 
     # run acs checks
     docker run -a STDOUT --volume $PWD/test/postman/helm:/etc/newman --network host postman/newman_alpine33:3.9.2 run "acs-test-helm-collection.json" --global-var "protocol=https" --global-var "url=$namespace.dev2.alfresco.me"
-    echo "TRAVIS_TEST_RESULT=${TRAVIS_TEST_RESULT}"
-    # run sync service checks
-    if [[ "$values_file" != "helm/alfresco-content-services/6.0.N_values.yaml" ]] && [[ "$values_file" != "helm/alfresco-content-services/community_values.yaml" ]]; then
-      docker run -a STDOUT --volume $PWD/test/postman/helm:/etc/newman --network host postman/newman_alpine33:3.9.2 run "sync-service-test-helm-collection.json" --global-var "protocol=https" --global-var "url=$namespace.dev.alfresco.me"
-      echo "TRAVIS_TEST_RESULT=${TRAVIS_TEST_RESULT}"
+    ACS_TEST_RESULT=$?
+    if [[ "${ACS_TEST_RESULT}" == "0" ]]; then
+      SYNC_TEST_RESULT=0
+      # run sync service checks
+      if [[ "$values_file" != "helm/alfresco-content-services/6.0.N_values.yaml" ]] && [[ "$values_file" != "helm/alfresco-content-services/community_values.yaml" ]]; then
+        docker run -a STDOUT --volume $PWD/test/postman/helm:/etc/newman --network host postman/newman_alpine33:3.9.2 run "sync-service-test-helm-collection.json" --global-var "protocol=https" --global-var "url=$namespace.dev.alfresco.me"
+        SYNC_TEST_RESULT=$?
+      fi
+
+      if [[ "${SYNC_TEST_RESULT}" == "0" ]]; then
+        # For checking if persistence failover is correctly working with our deployments
+        # in the next phase we delete the acs and postgress pods,
+        # wait for k8s to recreate them, then check if the data created in the first test run is still there
+        kubectl delete pod -l app=$release_name_acs-alfresco-cs-repository,component=repository -n $namespace
+        kubectl delete pod -l app=postgresql-acs,release=$release_name_acs -n $namespace
+        helm upgrade $release_name_acs helm/alfresco-content-services \
+        --wait \
+        --timeout 10m0s \
+        --atomic \
+        --reuse-values \
+        --namespace=$namespace
+
+        # check pods
+        pods_ready
+
+        # run checks after pod deletion
+        docker run -a STDOUT --volume $PWD/test/postman/helm:/etc/newman --network host postman/newman_alpine33:3.9.2 run "acs-validate-volume-collection.json" --global-var "protocol=https" --global-var "url=$namespace.dev.alfresco.me"
+      fi
     fi
-    # For checking if persistence failover is correctly working with our deployments
-    # in the next phase we delete the acs and postgress pods,
-    # wait for k8s to recreate them, then check if the data created in the first test run is still there
-    kubectl delete pod -l app=$release_name_acs-alfresco-cs-repository,component=repository -n $namespace
-    kubectl delete pod -l app=postgresql-acs,release=$release_name_acs -n $namespace
-    helm upgrade $release_name_acs helm/alfresco-content-services \
-    --wait \
-    --timeout 10m0s \
-    --atomic \
-    --reuse-values \
-    --namespace=$namespace
-
-    # check pods
-    pods_ready
-
-    # run checks after pod deletion
-    docker run -a STDOUT --volume $PWD/test/postman/helm:/etc/newman --network host postman/newman_alpine33:3.9.2 run "acs-validate-volume-collection.json" --global-var "protocol=https" --global-var "url=$namespace.dev.alfresco.me"
-    echo "TRAVIS_TEST_RESULT=${TRAVIS_TEST_RESULT}"
     fi
 _docker_deploy: &docker_deploy
   script: |
